services:
  php-apache:
    build:
      context: ./php-apache        
    ports:
      - "${PHP_APACHE_PORT}:80"
    volumes:
      - ../src:/var/www/html
    depends_on:
      - db   

  php-dev:
    build:
      context: ./php-dev
    volumes:
      - ../src:/var/www
    env_file:
      - .env    
    depends_on:
       - db

  # nginx:
  #   build:
  #     context: ./nginx
  #   ports:
  #     - "${NGINX_PORT}:80"
  #   volumes:
  #     - ../src:/var/www/html
  #   depends_on:
  #    - php
  # php:
  #  build:
  #    context: ./docker/php-fpm
  #  ports:
  #    - "9000:9000"
  #  expose:
  #   - 9000  # Porta do php-fpm      
  #  volumes:
  #    - ./src:/var/www/html
  #  depends_on:
  #    - db

  db:
    build:
      context: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # Volume nomeado do Docker
      #- ~/docker/volumes/mysql:/var/lib/mysql # Bind mount no diretório local

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
    - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db

volumes:
  mysql_data:  # Declarando o volume
    name: mysql_data
    external: true